import { defineStrings } from '../../lib/i18n';

// Copy for the "Hartă" tab. Shared words (cancel, retry, errors) come from i18n/core.ts.
export const MAP_STRINGS = defineStrings(
  {
    mapLabel: 'Hartă cu radarul de ploaie și pericolele raportate',
    controls: 'Controale hartă',
    layers: 'Straturi',
    locate: 'Locația mea',
    recenter: 'Centrează pe {place}',
    zoomIn: 'Mărește',
    zoomOut: 'Micșorează',
    loadingMap: 'Se încarcă harta…',
    layerRadar: 'Radar ploaie',
    layerRadarDesc: 'Ultimele 2 ore, animat',
    layerHazards: 'Pericole raportate',
    layerHazardsDesc: 'De la alți motocicliști',
    hazardsFailed: 'Pericolele nu s-au putut încărca acum.',
    opacity: 'Opacitate radar',
    layerForecast: 'Prognoză pe hartă',
    layerForecastDesc: 'Cum se mișcă norii și ploaia, ora cu oră',
    forecastOff: 'Fără',
    forecastCloud: 'Nori',
    forecastRain: 'Ploaie',
    forecastPlay: 'Pornește animația prognozei',
    forecastPause: 'Oprește animația prognozei',
    forecastScrubber: 'Ora afișată din prognoză',
    forecastNow: 'ora aceasta',
    forecastAhead: 'peste {h} h',
    forecastLoading: 'Se încarcă prognoza…',
    forecastUnavailable: 'Prognoza pe hartă nu e disponibilă acum.',
    forecastTag: 'PROGNOZĂ',
    forecastNote: 'Grilă de ~10 km: vezi fronturi, nu celule mici.',
    forecastLegendCloud: 'senin spre acoperit',
    forecastLegendRain: 'urme · slabă · moderată · puternică',
    radarPlay: 'Pornește animația radarului',
    radarPause: 'Oprește animația radarului',
    radarScrubber: 'Momentul afișat pe radar',
    radarObserved: 'RADAR',
    radarForecast: 'PROGNOZĂ',
    radarForecastWord: 'prognoză',
    radarLatest: 'cel mai recent',
    radarAgo: 'acum {min} min',
    radarJustNow: 'chiar acum',
    radarAhead: 'peste {min} min',
    radarLoading: 'Se încarcă radarul…',
    radarUnavailable: 'Radarul nu e disponibil acum.',
    radarNote: 'Radarul arată unde plouă acum. Șansele și cantitățile sunt pe',
    radarNoteLink: '„Acum”',
    legendLabel: 'Intensitatea ploii pe radar',
    legendLight: 'slabă',
    legendModerate: 'moderată',
    legendHeavy: 'puternică',
    legendExtreme: 'extremă',
    typeGravel: 'Pietriș',
    typeIce: 'Polei',
    typeFlood: 'Inundație',
    typeAccident: 'Accident',
    typeAnimals: 'Animale',
    typeRoadworks: 'Lucrări',
    typeOther: 'Alt pericol',
    sev1: 'Minor',
    sev2: 'Scăzut',
    sev3: 'Moderat',
    sev4: 'Ridicat',
    sev5: 'Sever',
    severity: 'Gravitate',
    hazardMarker: '{type}, gravitate {severity}',
    factDistance: 'Distanță',
    factReported: 'Raportat',
    factExpires: 'Expiră',
    distanceFrom: '{km} km de {place}',
    agoMin: 'acum {n} min',
    agoH: 'acum {n} h',
    agoDay: 'acum o zi',
    agoD: 'acum {n} zile',
    inMin: 'în {n} min',
    inH: 'în {n} h',
    inDay: 'într-o zi',
    inD: 'în {n} zile',
    atTime: '{rel}, la {time}',
    expired: 'a expirat',
    reportHere: 'Raportează aici',
    pickHint: 'Mută harta până când ținta e pe locul pericolului.',
    pickLongPress: 'Poți și să apeși lung pe hartă, direct pe loc.',
    pickConfirm: 'Aici e pericolul',
    reportTitle: 'Raportează un pericol',
    reportType: 'Ce fel de pericol?',
    reportTypeMissing: 'Alege tipul pericolului.',
    reportDesc: 'Descriere',
    reportDescHint: 'Ex.: pietriș în curba de la ieșirea din sat',
    reportDescShort: 'Scrie cel puțin 3 caractere.',
    reportDuration: 'Cât timp rămâne pe hartă',
    reportHours: '{n} h',
    reportSubmit: 'Trimite',
    reportDone: 'Pericol raportat. Mulțumim!',
    reportTooMany: 'Ai trimis prea multe rapoarte în ultima oră. Încearcă mai târziu.',
    reportSession: 'Sesiunea a expirat. Intră din nou în cont ca să raportezi.',
    reportInvalid: 'Serverul a respins raportul. Verifică tipul și descrierea.',
    reportSignedOut:
      'Ca să raportezi un pericol trebuie să fii în cont. Rapoartele sunt legate de cont, ca să nu poată fi folosite abuziv.',
    goToAccount: 'Intră în cont',
    locDenied: 'Accesul la locație e blocat. Permite-l din setările browserului.',
    locTimeout: 'Nu am primit poziția la timp. Încearcă din nou.',
    locUnsupported: 'Dispozitivul nu oferă locația.',
    locUnavailable: 'Locația nu e disponibilă acum.',
  },
  {
    mapLabel: 'Map with the rain radar and reported hazards',
    controls: 'Map controls',
    layers: 'Layers',
    locate: 'My location',
    recenter: 'Centre on {place}',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    loadingMap: 'Loading the map…',
    layerRadar: 'Rain radar',
    layerRadarDesc: 'Last 2 hours, animated',
    layerHazards: 'Reported hazards',
    layerHazardsDesc: 'From other riders',
    hazardsFailed: 'Hazards could not be loaded right now.',
    opacity: 'Radar opacity',
    layerForecast: 'Forecast on the map',
    layerForecastDesc: 'How the clouds and the rain move, hour by hour',
    forecastOff: 'Off',
    forecastCloud: 'Clouds',
    forecastRain: 'Rain',
    forecastPlay: 'Play the forecast',
    forecastPause: 'Pause the forecast',
    forecastScrubber: 'Forecast hour on screen',
    forecastNow: 'this hour',
    forecastAhead: 'in {h} h',
    forecastLoading: 'Loading the forecast…',
    forecastUnavailable: 'The forecast layer is not available right now.',
    forecastTag: 'FORECAST',
    forecastNote: 'A ~10 km grid: fronts show, single cells do not.',
    forecastLegendCloud: 'clear to overcast',
    forecastLegendRain: 'traces · light · moderate · heavy',
    radarPlay: 'Play the radar animation',
    radarPause: 'Pause the radar animation',
    radarScrubber: 'Radar time shown',
    radarObserved: 'RADAR',
    radarForecast: 'FORECAST',
    radarForecastWord: 'forecast',
    radarLatest: 'latest',
    radarAgo: '{min} min ago',
    radarJustNow: 'just now',
    radarAhead: 'in {min} min',
    radarLoading: 'Loading the radar…',
    radarUnavailable: 'The radar is not available right now.',
    radarNote: 'Radar shows where it is raining now. Chances and amounts are on',
    radarNoteLink: '"Now"',
    legendLabel: 'Rain intensity on the radar',
    legendLight: 'light',
    legendModerate: 'moderate',
    legendHeavy: 'heavy',
    legendExtreme: 'extreme',
    typeGravel: 'Gravel',
    typeIce: 'Ice',
    typeFlood: 'Flooding',
    typeAccident: 'Accident',
    typeAnimals: 'Animals',
    typeRoadworks: 'Roadworks',
    typeOther: 'Other hazard',
    sev1: 'Minor',
    sev2: 'Low',
    sev3: 'Moderate',
    sev4: 'High',
    sev5: 'Severe',
    severity: 'Severity',
    hazardMarker: '{type}, severity {severity}',
    factDistance: 'Distance',
    factReported: 'Reported',
    factExpires: 'Expires',
    distanceFrom: '{km} km from {place}',
    agoMin: '{n} min ago',
    agoH: '{n} h ago',
    agoDay: 'a day ago',
    agoD: '{n} days ago',
    inMin: 'in {n} min',
    inH: 'in {n} h',
    inDay: 'in a day',
    inD: 'in {n} days',
    atTime: '{rel}, at {time}',
    expired: 'expired',
    reportHere: 'Report here',
    pickHint: 'Move the map until the target is on the hazard.',
    pickLongPress: 'You can also long-press the map right on the spot.',
    pickConfirm: 'The hazard is here',
    reportTitle: 'Report a hazard',
    reportType: 'What kind of hazard?',
    reportTypeMissing: 'Choose the hazard type.',
    reportDesc: 'Description',
    reportDescHint: 'E.g. gravel in the bend leaving the village',
    reportDescShort: 'Write at least 3 characters.',
    reportDuration: 'How long it stays on the map',
    reportHours: '{n} h',
    reportSubmit: 'Send',
    reportDone: 'Hazard reported. Thank you!',
    reportTooMany: 'You sent too many reports in the last hour. Try again later.',
    reportSession: 'Your session expired. Sign in again to report.',
    reportInvalid: 'The server rejected the report. Check the type and description.',
    reportSignedOut: 'You need to be signed in to report a hazard. Reports are tied to an account so they cannot be abused.',
    goToAccount: 'Sign in',
    locDenied: 'Location access is blocked. Allow it in the browser settings.',
    locTimeout: 'No position received in time. Try again.',
    locUnsupported: 'This device does not provide a location.',
    locUnavailable: 'Location is not available right now.',
  },
);
