import { defineStrings } from '../../../lib/i18n';

// "Notificări" and "Alerte" sections. Counts are written as "label: {count}"
// so the sentence stays correct for 1 and for many.
export const ALERTS = defineStrings(
  {
    notifSection: 'Notificări',
    pushLabel: 'Push pe acest telefon',
    pushOn: 'Pornit. Dispozitive cu alerte: {count}.',
    pushOff: 'Alertele apar instant, ca notificare.',
    pushIos: 'Pe iPhone, notificările merg doar din aplicația instalată: Partajează, apoi „Adaugă pe ecranul principal”, și deschide MotoMeteo de acolo.',
    pushUnsupported: 'Browserul acesta nu suportă notificări push. Poți folosi alertele pe email.',
    pushDenied: 'Notificările sunt blocate pentru acest site. Permite-le din setările browserului (lacătul de lângă adresă), apoi încearcă din nou.',
    pushEnabled: 'Notificările push sunt pornite.',
    pushDisabled: 'Notificările push sunt oprite pe acest telefon.',
    pushFailed: 'Nu am putut porni notificările push.',
    emailLabel: 'Alerte pe email',
    emailOn: 'Primești email la {email} când apare o alertă.',
    emailOff: 'Oprite.',
    emailUnverified: 'Confirmă adresa ca să poți primi alerte pe email.',
    emailEnabled: 'Alertele pe email sunt pornite.',
    emailDisabled: 'Alertele pe email sunt oprite.',
    test: 'Trimite un test acum',
    testNote: 'Verifică acum următoarele 24 de ore la locația alertelor și trimite pe canalele active ce găsește.',
    testDisabled: 'Alertele sunt oprite. Pornește push sau email.',
    testNoLocation: 'Alege mai jos locația alertelor, apoi încearcă din nou.',
    testQuiet: 'Acum sunt orele de liniște: alertele pleacă după ce se termină.',
    testDelivered: 'Alerte trimise: {count}. Uită-te în notificări sau în email.',
    testNothing: 'Nicio alertă: următoarele 24 de ore sunt în pragurile tale.',
    testNoChannel: 'Sunt alerte, dar niciun canal nu e pornit. Pornește push sau email.',
    testAlready: 'Alertele găsite au fost trimise deja recent. Nu trimitem de două ori același lucru.',
    enableAlerts: 'Pornește alertele',
    alertsSection: 'Alerte',
    locationTitle: 'Locația alertelor',
    locationNone: 'Nesetată',
    locationMissing: 'Fără locație nu putem calcula alertele.',
    locationUse: 'Folosește locul curent',
    locationSame: 'E locul pe care îl vezi acum.',
    locationSaved: 'Alertele urmăresc acum {city}.',
    severityTitle: 'Ce alerte primești',
    sevLow: 'Doar EVITĂ',
    sevLowDesc: 'Numai situațiile periculoase: polei, rafale de 70+ km/h, ploaie cu impact mare.',
    sevMedium: 'ATENȚIE și EVITĂ',
    sevMediumDesc: 'Și situațiile la care trebuie să fii atent. Recomandat.',
    sevHigh: 'Toate',
    sevHighDesc: 'Inclusiv alertele informative, când scorul scade sub pragul tău.',
    thresholdsTitle: 'Praguri',
    minScore: 'Scor moto',
    minScoreValue: 'la {value} sau mai jos',
    gusts: 'Rafale de vânt',
    gustsValue: 'de la {value} km/h',
    cold: 'Frig',
    coldDesc: 'Temperatura aerului coboară la prag.',
    heat: 'Căldură',
    heatDesc: 'Temperatura aerului urcă la prag.',
    coldValue: 'la {value}°C sau mai jos',
    heatValue: 'la {value}°C sau mai sus',
    frost: 'Polei și carosabil înghețat',
    frostDesc: 'Mereu la nivel EVITĂ.',
    rainNote: 'Ploaia nu are prag de procent: alerta pornește când șansele și cantitatea împreună contează. De exemplu ploaie slabă cu peste 60% șanse, moderată de la 30% sau puternică la orice șansă.',
    quietTitle: 'Ore de liniște',
    quietDesc: 'Fără notificări între {start} și {end}, la ora locației.',
    quietStart: 'De la',
    quietEnd: 'Până la',
    quietSame: 'Început și sfârșit egale: orele de liniște nu se aplică.',
    emailCatsTitle: 'Pe email',
    emailCatsNote: 'Push primește toate alertele de nivelul ales. Aici alegi ce ajunge și pe email.',
    emailCatsOff: 'Pornește alertele pe email ca să alegi categoriile.',
    catScore: 'Scor moto scăzut',
    catWind: 'Rafale puternice',
    catRain: 'Ploaie',
    catTempLow: 'Frig',
    catTempHigh: 'Căldură',
    catFrost: 'Polei',
    catNeedsThreshold: 'Setează întâi pragul de mai sus.',
  },
  {
    notifSection: 'Notifications',
    pushLabel: 'Push on this phone',
    pushOn: 'On. Devices with alerts: {count}.',
    pushOff: 'Alerts show up instantly, as a notification.',
    pushIos: 'On iPhone, notifications only work from the installed app: Share, then “Add to Home Screen”, and open MotoMeteo from there.',
    pushUnsupported: 'This browser does not support push notifications. You can use email alerts.',
    pushDenied: 'Notifications are blocked for this site. Allow them in the browser settings (the lock next to the address), then try again.',
    pushEnabled: 'Push notifications are on.',
    pushDisabled: 'Push notifications are off on this phone.',
    pushFailed: 'Could not turn on push notifications.',
    emailLabel: 'Email alerts',
    emailOn: 'You get an email at {email} when an alert comes up.',
    emailOff: 'Off.',
    emailUnverified: 'Confirm your address to get email alerts.',
    emailEnabled: 'Email alerts are on.',
    emailDisabled: 'Email alerts are off.',
    test: 'Send a test now',
    testNote: 'Checks the next 24 hours at the alert location now and sends what it finds on the active channels.',
    testDisabled: 'Alerts are off. Turn on push or email.',
    testNoLocation: 'Pick the alert location below, then try again.',
    testQuiet: 'Quiet hours are on now: alerts go out once they end.',
    testDelivered: 'Alerts sent: {count}. Check your notifications or email.',
    testNothing: 'No alerts: the next 24 hours are within your limits.',
    testNoChannel: 'There are alerts, but no channel is on. Turn on push or email.',
    testAlready: 'The alerts found were already sent recently. We never send the same thing twice.',
    enableAlerts: 'Turn alerts on',
    alertsSection: 'Alerts',
    locationTitle: 'Alert location',
    locationNone: 'Not set',
    locationMissing: 'Without a location we cannot work out alerts.',
    locationUse: 'Use the current place',
    locationSame: 'It is the place you are looking at now.',
    locationSaved: 'Alerts now follow {city}.',
    severityTitle: 'Which alerts you get',
    sevLow: 'Only AVOID',
    sevLowDesc: 'Only dangerous conditions: ice, gusts of 70+ km/h, rain with high impact.',
    sevMedium: 'CAUTION and AVOID',
    sevMediumDesc: 'Also the conditions that need care. Recommended.',
    sevHigh: 'Everything',
    sevHighDesc: 'Including informative alerts when the score drops below your limit.',
    thresholdsTitle: 'Limits',
    minScore: 'Moto score',
    minScoreValue: 'at {value} or lower',
    gusts: 'Wind gusts',
    gustsValue: 'from {value} km/h',
    cold: 'Cold',
    coldDesc: 'Air temperature drops to the limit.',
    heat: 'Heat',
    heatDesc: 'Air temperature climbs to the limit.',
    coldValue: 'at {value}°C or lower',
    heatValue: 'at {value}°C or higher',
    frost: 'Ice and frozen roads',
    frostDesc: 'Always at AVOID level.',
    rainNote: 'Rain has no percentage limit: the alert fires when chance and amount together matter. For example light rain above 60%, moderate from 30%, or heavy at any chance.',
    quietTitle: 'Quiet hours',
    quietDesc: 'No notifications between {start} and {end}, local time at the location.',
    quietStart: 'From',
    quietEnd: 'Until',
    quietSame: 'Start and end are equal: quiet hours do not apply.',
    emailCatsTitle: 'By email',
    emailCatsNote: 'Push gets every alert of the chosen level. Here you pick what also goes to email.',
    emailCatsOff: 'Turn on email alerts to pick categories.',
    catScore: 'Low moto score',
    catWind: 'Strong gusts',
    catRain: 'Rain',
    catTempLow: 'Cold',
    catTempHigh: 'Heat',
    catFrost: 'Ice',
    catNeedsThreshold: 'Set the limit above first.',
  },
);
