import { defineStrings } from '../../../lib/i18n';

// Motorcycle, favourites, weekend ranking, app settings and the score explainer.
export const APP = defineStrings(
  {
    motoSection: 'Motocicletă',
    motoType: 'Tipul motocicletei',
    motoNaked: 'Naked',
    motoTouring: 'Touring',
    motoEnduro: 'Enduro',
    motoSport: 'Sport',
    motoScooter: 'Scuter',
    windTol: 'Toleranță la vânt',
    rainTol: 'Toleranță la ploaie',
    tolLow: 'Mică',
    tolMedium: 'Medie',
    tolHigh: 'Mare',
    comfort: 'Temperatura de confort',
    comfortValue: '{value}°C',
    motoLocal: 'Se păstrează pe acest telefon.',
    motoSynced: 'Se păstrează pe acest telefon și în cont.',
    favSection: 'Locuri favorite',
    favEmpty: 'Nu ai locuri favorite. Apasă steaua de lângă un loc ca să-l adaugi.',
    favCurrent: 'Acum',
    favShow: 'Arată vremea pentru {name}',
    favRemove: 'Scoate {name} din favorite',
    favRemoved: '{name} a fost scos din favorite.',
    undo: 'Anulează',
    favShown: 'Acum vezi vremea pentru {name}.',
    favSee: 'Vezi',
    weekendTitle: 'Unde merg în weekend',
    weekendLead: 'Compară scorul moto de sâmbătă și duminică pentru favoritele tale.',
    weekendNeedsFav: 'Adaugă cel puțin un loc favorit ca să compari.',
    weekendRun: 'Compară favoritele',
    weekendRerun: 'Compară din nou',
    weekendCancel: 'Oprește',
    weekendProgress: 'Se verifică {done} din {total}…',
    weekendNoData: 'fără date',
    weekendFailed: 'Nu am putut încărca prognoza pentru unele locuri ({count}).',
    noRain: 'fără ploaie',
    appSection: 'Aplicație',
    language: 'Limba',
    theme: 'Temă',
    themeDark: 'Cockpit',
    themeDay: 'Zi',
    themeNote: 'Zi: contrast mare, pentru soare puternic.',
    install: 'Instalează aplicația',
    installNote: 'Pornește din ecranul principal, merge și offline.',
    installed: 'Aplicația e instalată pe acest dispozitiv.',
    installIos: 'Pe iPhone: Partajează, apoi „Adaugă pe ecranul principal”.',
    installOther: 'Din meniul browserului alege „Instalează aplicația” sau „Adaugă pe ecranul principal”.',
    installDone: 'Gata, MotoMeteo se instalează.',
    privacy: 'Politica de confidențialitate',
    version: 'Versiune',
    scoreSection: 'Despre scor',
    scoreSummary: 'Cum citești scorul moto',
    scoreLead: 'Scorul, de la 0 la 100, spune cât de bine e de mers cu motocicleta la o anumită oră. Pornește de la 100 și scade pentru vânt în rafale, frig sau căldură, ploaie, ceață, polei și furtună.',
    tierFrom: 'de la {min}',
    tierBelow: 'sub {max}',
    tierIdealDesc: 'Condiții foarte bune.',
    tierOkDesc: 'Se poate merge, cu mici compromisuri.',
    tierAtentieDesc: 'Mergi doar dacă trebuie, cu grijă și echipament.',
    tierEvitaDesc: 'Mai bine amâni drumul.',
    scoreRain: 'Ploaia contează după șanse și cantitate împreună. 70% șanse de urme (sub 0,5 mm/h) abia pătează asfaltul, pe când 40% șanse de ploaie moderată te udă de-a binelea. De aceea vezi mereu ambele: „70% · urme”.',
  },
  {
    motoSection: 'Motorcycle',
    motoType: 'Motorcycle type',
    motoNaked: 'Naked',
    motoTouring: 'Touring',
    motoEnduro: 'Enduro',
    motoSport: 'Sport',
    motoScooter: 'Scooter',
    windTol: 'Wind tolerance',
    rainTol: 'Rain tolerance',
    tolLow: 'Low',
    tolMedium: 'Medium',
    tolHigh: 'High',
    comfort: 'Comfort temperature',
    comfortValue: '{value}°C',
    motoLocal: 'Kept on this phone.',
    motoSynced: 'Kept on this phone and in your account.',
    favSection: 'Favourite places',
    favEmpty: 'No favourites yet. Tap the star next to a place to add it.',
    favCurrent: 'Now',
    favShow: 'Show the weather for {name}',
    favRemove: 'Remove {name} from favourites',
    favRemoved: '{name} was removed from favourites.',
    undo: 'Undo',
    favShown: 'Now showing the weather for {name}.',
    favSee: 'View',
    weekendTitle: 'Where to ride this weekend',
    weekendLead: 'Compares the Saturday and Sunday moto score of your favourites.',
    weekendNeedsFav: 'Add at least one favourite place to compare.',
    weekendRun: 'Compare favourites',
    weekendRerun: 'Compare again',
    weekendCancel: 'Stop',
    weekendProgress: 'Checking {done} of {total}…',
    weekendNoData: 'no data',
    weekendFailed: 'Could not load the forecast for some places ({count}).',
    noRain: 'no rain',
    appSection: 'App',
    language: 'Language',
    theme: 'Theme',
    themeDark: 'Cockpit',
    themeDay: 'Day',
    themeNote: 'Day: high contrast, for strong sunlight.',
    install: 'Install the app',
    installNote: 'Starts from the home screen and works offline.',
    installed: 'The app is installed on this device.',
    installIos: 'On iPhone: Share, then “Add to Home Screen”.',
    installOther: 'In the browser menu pick “Install app” or “Add to Home screen”.',
    installDone: 'Done, MotoMeteo is installing.',
    privacy: 'Privacy policy',
    version: 'Version',
    scoreSection: 'About the score',
    scoreSummary: 'How to read the moto score',
    scoreLead: 'The score, from 0 to 100, says how good an hour is for riding. It starts at 100 and drops for gusty wind, cold or heat, rain, fog, ice and storms.',
    tierFrom: 'from {min}',
    tierBelow: 'below {max}',
    tierIdealDesc: 'Very good conditions.',
    tierOkDesc: 'Fine to ride, with small compromises.',
    tierAtentieDesc: 'Ride only if you must, carefully and well equipped.',
    tierEvitaDesc: 'Better to postpone the ride.',
    scoreRain: 'Rain counts by chance and amount together. A 70% chance of traces (under 0.5 mm/h) barely marks the tarmac, while a 40% chance of moderate rain soaks you. That is why you always see both: “70% · traces”.',
  },
);
