import { defineStrings } from '../../../lib/i18n';

// Signed-out auth card and the password reset view.
export const AUTH = defineStrings(
  {
    title: 'Eu',
    subtitle: 'Cont, alerte și setări',
    authTitle: 'Intră în cont',
    authLead: 'Contul e gratuit. Setările de pe acest telefon merg și fără el.',
    modeLabel: 'Cum intri în cont',
    modeLogin: 'Intră',
    modeCode: 'Cod pe email',
    modeSignup: 'Cont nou',
    modeForgot: 'Am uitat parola',
    login: 'Intră în cont',
    welcome: 'Bine ai revenit.',
    forgotLink: 'Am uitat parola',
    codeLead: 'Îți trimitem un cod de 6 cifre. Nu ai nevoie de parolă.',
    sendCode: 'Trimite codul',
    codeSent: 'Am trimis un cod la {email}. Expiră în 10 minute.',
    codeLabel: 'Codul din email',
    codeHint: '6 cifre',
    verifyCode: 'Confirmă codul',
    resendCode: 'Retrimite codul',
    otherEmail: 'Alt email',
    codeNote: 'Dacă adresa avea un cont neconfirmat, codul îl confirmă: parola veche se șterge și celelalte sesiuni se închid.',
    nameLabel: 'Nume afișat (opțional)',
    passwordNewHint: 'Minimum 8 caractere.',
    signup: 'Creează contul',
    signupDone: 'Cont creat. Ți-am trimis un link de confirmare pe email.',
    signupDoneNoMail: 'Cont creat.',
    existsLogin: 'Intră cu parola',
    existsForgot: 'Resetează parola',
    forgotLead: 'Îți trimitem un link ca să alegi o parolă nouă.',
    sendReset: 'Trimite linkul',
    resetSent: 'Dacă există un cont pentru {email}, primești în câteva minute un link valabil 30 de minute. Verifică și folderul Spam.',
    backToLogin: 'Înapoi la intrare',
    unlocksTitle: 'Ce primești cu un cont',
    unlockAlerts: 'Alerte push și pe email când vremea se strică la tine',
    unlockRoutes: 'Trasee salvate, pe orice dispozitiv',
    unlockStats: 'Statistici ale drumurilor tale',
    unlockHazards: 'Raportezi pericole pe drum pentru ceilalți motocicliști',
    resetTitle: 'Parolă nouă',
    resetLead: 'Alege o parolă nouă pentru contul tău.',
    newPassword: 'Parola nouă',
    confirmPassword: 'Repetă parola',
    mismatch: 'Parolele nu coincid.',
    savePassword: 'Salvează parola',
    resetDone: 'Parola a fost schimbată. Din motive de siguranță am închis toate sesiunile: intră din nou cu parola nouă.',
    goSignIn: 'Intră în cont',
    resetInvalidLead: 'Cere un link nou mai jos. Linkurile sunt valabile 30 de minute și merg o singură dată.',
    backToApp: 'Înapoi la aplicație',
  },
  {
    title: 'Me',
    subtitle: 'Account, alerts and settings',
    authTitle: 'Sign in',
    authLead: 'The account is free. Settings on this phone work without it too.',
    modeLabel: 'How to sign in',
    modeLogin: 'Sign in',
    modeCode: 'Email code',
    modeSignup: 'New account',
    modeForgot: 'Forgot password',
    login: 'Sign in',
    welcome: 'Welcome back.',
    forgotLink: 'Forgot password',
    codeLead: 'We send you a 6-digit code. No password needed.',
    sendCode: 'Send code',
    codeSent: 'We sent a code to {email}. It expires in 10 minutes.',
    codeLabel: 'Code from the email',
    codeHint: '6 digits',
    verifyCode: 'Confirm code',
    resendCode: 'Send again',
    otherEmail: 'Other email',
    codeNote: 'If the address had an unconfirmed account, the code confirms it: the old password is removed and other sessions are closed.',
    nameLabel: 'Display name (optional)',
    passwordNewHint: 'At least 8 characters.',
    signup: 'Create account',
    signupDone: 'Account created. We sent you a confirmation link by email.',
    signupDoneNoMail: 'Account created.',
    existsLogin: 'Sign in with password',
    existsForgot: 'Reset password',
    forgotLead: 'We send you a link to choose a new password.',
    sendReset: 'Send link',
    resetSent: 'If there is an account for {email}, a link valid for 30 minutes arrives in a few minutes. Check the Spam folder too.',
    backToLogin: 'Back to sign in',
    unlocksTitle: 'What an account gives you',
    unlockAlerts: 'Push and email alerts when the weather turns where you ride',
    unlockRoutes: 'Saved routes, on any device',
    unlockStats: 'Stats of your rides',
    unlockHazards: 'Report road hazards for other riders',
    resetTitle: 'New password',
    resetLead: 'Choose a new password for your account.',
    newPassword: 'New password',
    confirmPassword: 'Repeat the password',
    mismatch: 'The passwords do not match.',
    savePassword: 'Save password',
    resetDone: 'Password changed. For safety we closed every session: sign in again with the new password.',
    goSignIn: 'Sign in',
    resetInvalidLead: 'Ask for a new link below. Links are valid for 30 minutes and work once.',
    backToApp: 'Back to the app',
  },
);
