import { defineStrings } from '../../../lib/i18n';

// Words shared by several parts of the account feature, plus error messages.
export const COMMON = defineStrings(
  {
    saved: 'Salvat.',
    showPassword: 'Arată parola',
    hidePassword: 'Ascunde parola',
    emailLabel: 'Email',
    passwordLabel: 'Parolă',
    emailInvalid: 'Scrie o adresă de email validă.',
    passwordShort: 'Parola trebuie să aibă cel puțin 8 caractere.',
    passwordLong: 'Parola e prea lungă (maximum 256 de caractere).',
    errNetwork: 'Nu am putut contacta serverul. Verifică conexiunea și încearcă din nou.',
    errRateLimit: 'Prea multe încercări într-un timp scurt. Așteaptă câteva minute.',
    errWrongCredentials: 'Email sau parolă greșită.',
    errEmailExists: 'Există deja un cont cu acest email.',
    errCodeInvalid: 'Codul nu e corect. Verifică cele 6 cifre.',
    errCodeExpired: 'Codul a expirat sau a fost deja folosit. Cere unul nou.',
    errCodeExhausted: 'Prea multe coduri greșite. Cere un cod nou.',
    errResetLink: 'Linkul de resetare a expirat sau a fost deja folosit.',
    errWrongPassword: 'Parola curentă nu e corectă.',
    errEmailTaken: 'Adresa e deja folosită de alt cont.',
    errInvalidInput: 'Unele date nu sunt valide. Verifică și încearcă din nou.',
    errSession: 'Sesiunea a expirat. Intră din nou în cont.',
    errUnavailable: 'Serviciul e temporar indisponibil. Încearcă din nou în câteva momente.',
    errGeneric: 'Ceva n-a mers. Încearcă din nou.',
  },
  {
    saved: 'Saved.',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    emailInvalid: 'Enter a valid email address.',
    passwordShort: 'The password needs at least 8 characters.',
    passwordLong: 'The password is too long (256 characters at most).',
    errNetwork: 'Could not reach the server. Check your connection and try again.',
    errRateLimit: 'Too many attempts in a short time. Wait a few minutes.',
    errWrongCredentials: 'Wrong email or password.',
    errEmailExists: 'An account with this email already exists.',
    errCodeInvalid: 'That code is not right. Check the 6 digits.',
    errCodeExpired: 'The code expired or was already used. Ask for a new one.',
    errCodeExhausted: 'Too many wrong codes. Ask for a new one.',
    errResetLink: 'The reset link has expired or was already used.',
    errWrongPassword: 'The current password is not right.',
    errEmailTaken: 'That address is already used by another account.',
    errInvalidInput: 'Some details are not valid. Check them and try again.',
    errSession: 'Your session expired. Sign in again.',
    errUnavailable: 'The service is briefly unavailable. Try again in a moment.',
    errGeneric: 'Something went wrong. Try again.',
  },
);
