import { defineStrings } from '../../../lib/i18n';

// Signed-in header, the "Cont" section and its sheets.
export const PROFILE = defineStrings(
  {
    verified: 'Confirmat',
    unverified: 'Neconfirmat',
    memberSince: 'Cont din {date}',
    unverifiedNote: 'Confirmă adresa din emailul primit, ca să o poți folosi la resetarea parolei. După confirmare vei intra din nou în cont.',
    resend: 'Retrimite linkul',
    resendDone: 'Ți-am trimis un link nou la {email}.',
    resendAlready: 'Adresa e deja confirmată.',
    loadError: 'Nu am putut încărca contul.',
    section: 'Cont',
    nameRow: 'Nume afișat',
    emailRow: 'Email',
    passwordRow: 'Parolă',
    passwordRowValue: 'Schimbă',
    logout: 'Ieși din cont',
    logoutDone: 'Ai ieșit din cont.',
    deleteRow: 'Șterge contul',
    nameTitle: 'Nume afișat',
    nameEmpty: 'Scrie un nume.',
    nameSaved: 'Numele a fost salvat.',
    emailTitle: 'Schimbă emailul',
    newEmail: 'Email nou',
    currentPassword: 'Parola curentă',
    passwordRequired: 'Scrie parola curentă.',
    emailSame: 'Aceasta e deja adresa contului.',
    emailChange: 'Schimbă emailul',
    emailChanged: 'Ți-am trimis un link de confirmare la {email}. Celelalte dispozitive au fost deconectate.',
    understood: 'Am înțeles',
    noPasswordHint: 'Ai intrat cu cod pe email și n-ai parolă?',
    setByEmail: 'Setează parola prin email',
    setByEmailSent: 'Ți-am trimis la {email} un link pentru parolă. După ce o setezi, intri din nou în cont.',
    passwordTitle: 'Schimbă parola',
    passwordChange: 'Schimbă parola',
    passwordChanged: 'Parola a fost schimbată. Celelalte dispozitive au fost deconectate.',
    deleteTitle: 'Șterge contul',
    deleteLead: 'Se șterg definitiv contul, setările de alerte, dispozitivele cu push, traseele salvate, istoricul drumurilor și pericolele raportate. Nu se poate anula.',
    deleteLocal: 'Favoritele și setările de pe acest telefon rămân.',
    deleteType: 'Scrie {word} ca să confirmi',
    deleteConfirm: 'Șterge definitiv',
    deleteDone: 'Contul a fost șters.',
  },
  {
    verified: 'Confirmed',
    unverified: 'Not confirmed',
    memberSince: 'Account since {date}',
    unverifiedNote: 'Confirm the address from the email we sent, so that you can use it to reset your password. After confirming you sign in again.',
    resend: 'Resend link',
    resendDone: 'We sent a new link to {email}.',
    resendAlready: 'The address is already confirmed.',
    loadError: 'Could not load your account.',
    section: 'Account',
    nameRow: 'Display name',
    emailRow: 'Email',
    passwordRow: 'Password',
    passwordRowValue: 'Change',
    logout: 'Sign out',
    logoutDone: 'You are signed out.',
    deleteRow: 'Delete account',
    nameTitle: 'Display name',
    nameEmpty: 'Enter a name.',
    nameSaved: 'Name saved.',
    emailTitle: 'Change email',
    newEmail: 'New email',
    currentPassword: 'Current password',
    passwordRequired: 'Enter your current password.',
    emailSame: 'That is already the account address.',
    emailChange: 'Change email',
    emailChanged: 'We sent a confirmation link to {email}. Other devices were signed out.',
    understood: 'Got it',
    noPasswordHint: 'Signed in with an email code and have no password?',
    setByEmail: 'Set a password by email',
    setByEmailSent: 'We sent a password link to {email}. Once it is set, you sign in again.',
    passwordTitle: 'Change password',
    passwordChange: 'Change password',
    passwordChanged: 'Password changed. Other devices were signed out.',
    deleteTitle: 'Delete account',
    deleteLead: 'This permanently deletes the account, alert settings, push devices, saved routes, ride history and reported hazards. It cannot be undone.',
    deleteLocal: 'Favourites and settings on this phone stay.',
    deleteType: 'Type {word} to confirm',
    deleteConfirm: 'Delete for good',
    deleteDone: 'The account was deleted.',
  },
);
