import { defineStrings } from '../../lib/i18n';

// Copy of the sheets opened from the "Acum" screen.
export const S_SHEETS = defineStrings(
  {
    rainSheetTitle: 'Cum citești ploaia',
    rainSheetIntro: 'Două numere diferite, care nu se înlocuiesc unul pe altul. Le arătăm mereu împreună.',
    chanceKey: 'Șanse',
    chanceDef: 'În {n} din 10 scenarii ale modelelor meteo cade măcar 0,1 mm în ora aceea.',
    chanceDefNote: 'Spune cât de sigur e că plouă. Nu spune cât.',
    amountKey: 'Cantitate',
    amountDef: 'Câți milimetri cad într-o oră, dacă plouă. 1 mm înseamnă 1 litru pe m².',
    amountDefNote: 'Spune cât de ud va fi asfaltul.',
    bandsTitle: 'Intensitate și ce înseamnă pe moto',
    effectUrme: 'câteva picături, asfaltul abia se pătează',
    effectSlaba: 'asfalt ud, frânare mai lungă, marcaje alunecoase',
    effectModerata: 'costum de ploaie, vizibilitate redusă, stropi de la mașini',
    effectPuternica: 'risc de acvaplanare, amână drumul',
    matrixTitle: 'Cum intră în scor',
    matrixCaption: 'Rânduri: șansele. Coloane: intensitatea. Culoarea arată cât scade scorul.',
    rowLow: 'sub 30%',
    rowMid: '30–60%',
    rowHigh: 'peste 60%',
    legendNone: 'nu contează',
    legendLow: 'scade puțin',
    legendMedium: 'atenție',
    legendHigh: 'evită',
    matrixNow: 'ACUM',
    thresholdsNote: 'Pragurile urmează clasificarea standard a intensității ploii: slabă sub 2,5 mm/h, moderată până la 7,5 mm/h, puternică peste. „Urme” e pragul nostru sub 0,5 mm/h.',
    gotIt: 'Am înțeles',
    scoreSheetTitle: 'De ce scorul {score}',
    scoreIntro: 'Scorul pornește de la 100. Fiecare factor scade puncte, iar unii pun și un plafon peste care scorul nu poate trece.',
    scoreNoFactors: 'Nimic nu scade scorul: condiții bune pe toate criteriile.',
    scoreMath: 'Calcul: 100 − {penalty} = {raw}',
    scoreMathCap: 'Calcul: 100 − {penalty} = {raw}, limitat la {cap}',
    penalty: '−{n} puncte',
    capTag: 'maxim {n}',
    factorRain: 'Ploaie',
    factorStorm: 'Furtună',
    factorSnow: 'Ninsoare',
    factorIce: 'Ploaie care îngheață',
    factorFog: 'Ceață',
    factorWind: 'Rafale',
    factorCold: 'Frig',
    factorHeat: 'Căldură',
    factorColdWet: 'Frig și umezeală',
    factorFrost: 'Polei pe carosabil',
    factorOther: 'Alt factor',
    whyScore: 'De ce {score}',
    temperature: 'Temperatură',
    rain: 'Ploaie',
    wind: 'Rafale',
    clouds: 'Nori',
    road: 'Asfalt',
    humidity: 'Umiditate',
    visibility: 'Vizibilitate',
    uv: 'UV',
    dry: 'uscat',
    colHour: 'Ora',
    colSky: 'Cer',
    colTemp: 'Temp.',
    colGust: 'Rafale',
    colRain: 'Ploaie',
    colScore: 'Scor',
    sunrise: 'Răsărit {t}',
    sunset: 'Apus {t}',
    noHours: 'Nu avem prognoză pe ore pentru ziua asta.',
    hourlyTitle: 'Pe ore',
  },
  {
    rainSheetTitle: 'How to read rain',
    rainSheetIntro: 'Two different numbers that do not replace each other. We always show them together.',
    chanceKey: 'Chance',
    chanceDef: 'In {n} out of 10 weather model scenarios at least 0.1 mm falls in that hour.',
    chanceDefNote: 'It tells how sure the rain is. Not how much.',
    amountKey: 'Amount',
    amountDef: 'How many millimetres fall in an hour, if it rains. 1 mm is 1 litre per m².',
    amountDefNote: 'It tells how wet the asphalt gets.',
    bandsTitle: 'Intensity and what it means on a bike',
    effectUrme: 'a few drops, the asphalt barely spots',
    effectSlaba: 'wet asphalt, longer braking, slippery markings',
    effectModerata: 'rain suit, poor visibility, spray from cars',
    effectPuternica: 'aquaplaning risk, postpone the ride',
    matrixTitle: 'How it enters the score',
    matrixCaption: 'Rows: the chance. Columns: the intensity. The colour shows how much the score drops.',
    rowLow: 'below 30%',
    rowMid: '30–60%',
    rowHigh: 'above 60%',
    legendNone: 'no effect',
    legendLow: 'small drop',
    legendMedium: 'caution',
    legendHigh: 'avoid',
    matrixNow: 'NOW',
    thresholdsNote: 'Thresholds follow the standard rain intensity classes: light below 2.5 mm/h, moderate up to 7.5 mm/h, heavy above. "Traces" is our own band below 0.5 mm/h.',
    gotIt: 'Got it',
    scoreSheetTitle: 'Why the score is {score}',
    scoreIntro: 'The score starts at 100. Each factor takes points off, and some also set a ceiling the score cannot go above.',
    scoreNoFactors: 'Nothing lowers the score: good conditions on every criterion.',
    scoreMath: 'Maths: 100 − {penalty} = {raw}',
    scoreMathCap: 'Maths: 100 − {penalty} = {raw}, capped at {cap}',
    penalty: '−{n} points',
    capTag: 'max {n}',
    factorRain: 'Rain',
    factorStorm: 'Thunderstorm',
    factorSnow: 'Snow',
    factorIce: 'Freezing rain',
    factorFog: 'Fog',
    factorWind: 'Gusts',
    factorCold: 'Cold',
    factorHeat: 'Heat',
    factorColdWet: 'Cold and wet',
    factorFrost: 'Black ice on the road',
    factorOther: 'Other factor',
    whyScore: 'Why {score}',
    temperature: 'Temperature',
    rain: 'Rain',
    wind: 'Gusts',
    clouds: 'Clouds',
    road: 'Asphalt',
    humidity: 'Humidity',
    visibility: 'Visibility',
    uv: 'UV',
    dry: 'dry',
    colHour: 'Hour',
    colSky: 'Sky',
    colTemp: 'Temp.',
    colGust: 'Gusts',
    colRain: 'Rain',
    colScore: 'Score',
    sunrise: 'Sunrise {t}',
    sunset: 'Sunset {t}',
    noHours: 'No hourly forecast for this day.',
    hourlyTitle: 'By the hour',
  },
);
