import { defineStrings } from '../../lib/i18n';

// "Surse de date": which services the numbers on "Acum" come from.
export const S_SOURCES = defineStrings(
  {
    title: 'Surse de date',
    intro: 'Valorile de acum sunt combinate din sursele de mai jos. O sursă fără date nu strică nimic: aplicația folosește ce a răspuns.',
    fallback: 'Serverul MotoMeteo nu a răspuns, așa că prognoza vine direct de la Open-Meteo.',
    groupStations: 'Măsurători',
    groupModels: 'Modele de prognoză',
    groupWarnings: 'Avertizări',
    groupMap: 'Pe hartă',
    statusUsed: 'Folosită',
    statusNoData: 'Fără date acum',
    statusNoneNearby: 'Nimic aproape',
    statusOff: 'Neconfigurată',
    licence: 'Sursa și condițiile',
    stationDetail: '{station} · {km} km · măsurat {ago}',
    stationNoTime: '{station} · {km} km',
    ago: 'acum {min} min',
    agoHours: 'acum {h} h',
    modelsDetail: 'Au răspuns {n} modele',
    membersDetail: '{n} rulări',
    warningsSome: 'Avertizări pentru acest loc: {n}',
    warningsNone: 'Nicio avertizare pentru acest loc acum',
    'official-stations.name': 'Stații meteo oficiale ANM',
    'official-stations.role': 'Temperatură, vânt, rafale și ploaie măsurate la cea mai apropiată stație oficială (prin EUMETNET MeteoGate), actualizate din oră în oră.',
    'metar.name': 'Aeroporturi (METAR)',
    'metar.role': 'Ce se întâmplă acum la cel mai apropiat aeroport: ploaie, furtună, ceață și vizibilitatea (NOAA).',
    'weatherxm.name': 'WeatherXM',
    'weatherxm.role': 'Stație din rețeaua WeatherXM, când există una aproape.',
    'netatmo.name': 'Netatmo',
    'netatmo.role': 'Stații meteo publice ale utilizatorilor Netatmo din apropiere.',
    'open-meteo.name': 'Open-Meteo',
    'open-meteo.role': 'Prognoza de bază: orele, zilele, răsăritul și apusul.',
    'model-ensemble.name': 'Șase modele naționale',
    'model-ensemble.role': 'ECMWF, ICON (Germania), GFS (SUA), Météo-France, Met Office și GEM (Canada), comparate oră cu oră pentru încrederea în prognoză și votul pe ploaie.',
    'rain-ensemble.name': 'Prognoze ansamblu pentru ploaie',
    'rain-ensemble.role': 'Peste 100 de rulări ICON-EU, ECMWF și GFS. Partea care dă ploaie devine șansa de ploaie a orei.',
    'openweathermap.name': 'OpenWeatherMap',
    'openweathermap.role': 'Condiții curente, descrierea vremii și șansa de ploaie pe ore.',
    'met-norway.name': 'MET Norway',
    'met-norway.role': 'Condiții curente, prognoza pe zile și ploaia pe ore.',
    'pirate-weather.name': 'Pirate Weather',
    'pirate-weather.role': 'Condiții curente și șansa de ploaie pe ore.',
    'anm-nowcast.name': 'ANM, avertizări nowcasting',
    'anm-nowcast.role': 'Avertizări pentru următoarele 30-90 de minute (averse, furtuni, grindină), pe zona desenată de meteorologi.',
    'meteoalarm.name': 'Meteoalarm',
    'meteoalarm.role': 'Avertizările ANM pe județe, cu coduri galben, portocaliu și roșu.',
    'rainviewer.name': 'RainViewer',
    'rainviewer.role': 'Radarul pe ultimele 2 ore.',
    'dwd.name': 'DWD, modelul ICON-EU',
    'dwd.role': 'Ploaia prognozată pe hartă, la 7 km.',
    'eumetsat.name': 'EUMETSAT',
    'eumetsat.role': 'Norii și fulgerele văzute de sateliții Meteosat.',
    'osm.name': 'OpenStreetMap',
    'osm.role': 'Harta de bază și căutarea locurilor (prin Photon).',
  },
  {
    title: 'Data sources',
    intro: 'The values for now are combined from the sources below. A source without data spoils nothing: the app uses whatever answered.',
    fallback: 'The MotoMeteo server did not answer, so the forecast comes straight from Open-Meteo.',
    groupStations: 'Measurements',
    groupModels: 'Forecast models',
    groupWarnings: 'Warnings',
    groupMap: 'On the map',
    statusUsed: 'Used',
    statusNoData: 'No data now',
    statusNoneNearby: 'Nothing nearby',
    statusOff: 'Not set up',
    licence: 'Source and terms',
    stationDetail: '{station} · {km} km · measured {ago}',
    stationNoTime: '{station} · {km} km',
    ago: '{min} min ago',
    agoHours: '{h} h ago',
    modelsDetail: '{n} models answered',
    membersDetail: '{n} runs',
    warningsSome: 'Warnings for this place: {n}',
    warningsNone: 'No warning for this place right now',
    'official-stations.name': 'Official ANM weather stations',
    'official-stations.role': 'Temperature, wind, gusts and rain measured at the nearest official station (through EUMETNET MeteoGate), updated hourly.',
    'metar.name': 'Airports (METAR)',
    'metar.role': 'What is happening now at the nearest airport: rain, storm, fog and visibility (NOAA).',
    'weatherxm.name': 'WeatherXM',
    'weatherxm.role': 'A WeatherXM network station, when there is one nearby.',
    'netatmo.name': 'Netatmo',
    'netatmo.role': 'Public weather stations of Netatmo owners nearby.',
    'open-meteo.name': 'Open-Meteo',
    'open-meteo.role': 'The base forecast: hours, days, sunrise and sunset.',
    'model-ensemble.name': 'Six national models',
    'model-ensemble.role': 'ECMWF, ICON (Germany), GFS (USA), Météo-France, the Met Office and GEM (Canada), compared hour by hour for how sure the forecast is and for the rain vote.',
    'rain-ensemble.name': 'Rain ensemble forecasts',
    'rain-ensemble.role': 'Over 100 ICON-EU, ECMWF and GFS runs. The share that gives rain becomes the hour’s chance of rain.',
    'openweathermap.name': 'OpenWeatherMap',
    'openweathermap.role': 'Current conditions, the weather description and the hourly chance of rain.',
    'met-norway.name': 'MET Norway',
    'met-norway.role': 'Current conditions, the daily forecast and hourly rain.',
    'pirate-weather.name': 'Pirate Weather',
    'pirate-weather.role': 'Current conditions and the hourly chance of rain.',
    'anm-nowcast.name': 'ANM nowcasting warnings',
    'anm-nowcast.role': 'Warnings for the next 30 to 90 minutes (downpours, storms, hail), over the area the forecasters drew.',
    'meteoalarm.name': 'Meteoalarm',
    'meteoalarm.role': 'ANM county warnings, in yellow, orange and red.',
    'rainviewer.name': 'RainViewer',
    'rainviewer.role': 'The radar over the last 2 hours.',
    'dwd.name': 'DWD, ICON-EU model',
    'dwd.role': 'Forecast rain on the map, at 7 km.',
    'eumetsat.name': 'EUMETSAT',
    'eumetsat.role': 'Clouds and lightning seen by the Meteosat satellites.',
    'osm.name': 'OpenStreetMap',
    'osm.role': 'The base map and place search (through Photon).',
  },
);
