import { defineStrings } from '../../lib/i18n';

// Copy of the "Acum" screen itself (hero, timeline, cards, lists).
export const S_NOW = defineStrings(
  {
    scoreAria: 'Scor moto {score} din 100, {tier}. Atinge pentru explicație.',
    alertsTitle: 'Avertizări oficiale',
    alertFallbackTitle: 'Avertizare meteo',
    alertPeriod: '{from} – {to}',
    alertUntil: 'până la {to}',
    alertMore: 'Detalii',
    alertLess: 'Ascunde',
    alertSource: 'sursă: {sender}',
    scoreAriaNone: 'Fără scor moto acum.',
    windowLabel: 'Cea mai bună fereastră',
    windowToday: 'azi {from}–{to} · {score}',
    windowTomorrow: 'mâine {from}–{to} · {score}',
    timelineTitle: 'Următoarele 24 h',
    timelineHint: 'trage pentru detalii',
    timelineAria: 'Scor moto pe ore. Săgețile schimbă ora, Enter deschide detaliile.',
    nowLabel: 'ACUM',
    nightLabel: 'NOAPTE',
    rainLane: 'Cât plouă',
    laneMax: 'maxim {mm} mm/h',
    hourDetails: 'Detalii pentru {hour}',
    rainTitle: 'Ploaie',
    rainNext24: 'Următoarele 24 h',
    rainNowUntil: 'Acum – {to}',
    rainSpan: '{from} – {to}',
    chance: 'Șanse să plouă',
    amount: 'Cât plouă',
    peakAt: 'maxim, la {hour}',
    bandPeakAt: '{band} · maxim la {hour}',
    noRain: 'nu plouă',
    rainInfo: 'Cum citești ploaia',
    scaleBelow: 'sub {v}',
    scaleAbove: 'peste {v}',
    air: 'Aer',
    gusts: 'Rafale',
    asphalt: 'Asfalt',
    feels: 'resimțit {t}',
    more: 'Mai multe',
    less: 'Mai puține',
    humidity: 'Umiditate',
    pressure: 'Presiune',
    visibility: 'Vizibilitate',
    uv: 'Indice UV',
    aqi: 'Calitatea aerului',
    pollen: 'Polen',
    dewPoint: 'Punct de rouă',
    windAvg: 'Vânt mediu',
    beaufort: '{b} pe scara Beaufort',
    gearToday: 'Echipament azi',
    gearTomorrow: 'Echipament mâine',
    gearCount: '{done} din {total}',
    daysTitle: 'Următoarele {n} zile',
    moreDays: 'Arată 14 zile',
    fewerDays: 'Arată 7 zile',
    today: 'Azi',
    tomorrow: 'Mâine',
    dayAria: '{day}: scor {score}, {temps}, {rain}. Vezi orele.',
    errorTitle: 'Nu am putut încărca vremea',
    staleError: 'Nu am putut actualiza datele. Vezi ultima variantă primită.',
  },
  {
    scoreAria: 'Ride score {score} out of 100, {tier}. Tap for the explanation.',
    alertsTitle: 'Official warnings',
    alertFallbackTitle: 'Weather warning',
    alertPeriod: '{from} – {to}',
    alertUntil: 'until {to}',
    alertMore: 'Details',
    alertLess: 'Hide',
    alertSource: 'source: {sender}',
    scoreAriaNone: 'No ride score right now.',
    windowLabel: 'Best window',
    windowToday: 'today {from}–{to} · {score}',
    windowTomorrow: 'tomorrow {from}–{to} · {score}',
    timelineTitle: 'Next 24 h',
    timelineHint: 'drag for details',
    timelineAria: 'Hourly ride score. Arrow keys change the hour, Enter opens the details.',
    nowLabel: 'NOW',
    nightLabel: 'NIGHT',
    rainLane: 'How much rain',
    laneMax: 'peak {mm} mm/h',
    hourDetails: 'Details for {hour}',
    rainTitle: 'Rain',
    rainNext24: 'Next 24 h',
    rainNowUntil: 'Now – {to}',
    rainSpan: '{from} – {to}',
    chance: 'Chance of rain',
    amount: 'How much',
    peakAt: 'peak, at {hour}',
    bandPeakAt: '{band} · peak at {hour}',
    noRain: 'no rain',
    rainInfo: 'How to read rain',
    scaleBelow: 'below {v}',
    scaleAbove: 'above {v}',
    air: 'Air',
    gusts: 'Gusts',
    asphalt: 'Asphalt',
    feels: 'feels like {t}',
    more: 'More',
    less: 'Less',
    humidity: 'Humidity',
    pressure: 'Pressure',
    visibility: 'Visibility',
    uv: 'UV index',
    aqi: 'Air quality',
    pollen: 'Pollen',
    dewPoint: 'Dew point',
    windAvg: 'Mean wind',
    beaufort: '{b} on the Beaufort scale',
    gearToday: 'Gear for today',
    gearTomorrow: 'Gear for tomorrow',
    gearCount: '{done} of {total}',
    daysTitle: 'Next {n} days',
    moreDays: 'Show 14 days',
    fewerDays: 'Show 7 days',
    today: 'Today',
    tomorrow: 'Tomorrow',
    dayAria: '{day}: score {score}, {temps}, {rain}. See the hours.',
    errorTitle: 'Could not load the weather',
    staleError: 'Could not refresh the data. Showing the last version received.',
  },
);
