import { defineStrings } from '../../../lib/i18n';

// Gear checklist copy, ported from the legacy app's gearRecommendationClient
// strings (gi_* / gr_*) and shortened for a checklist.
export const GEAR_TEXTS = defineStrings(
  {
    rain_suit: 'Costum de ploaie',
    rain_gloves: 'Mănuși impermeabile',
    pinlock: 'Pinlock anti-aburire și lavetă pentru vizor',
    jacket_winter: 'Geacă de iarnă cu protecții CE și liner termic',
    base_full: 'Strat termic complet (bluză și pantaloni)',
    jacket_liner: 'Geacă 3 sezoane cu liner termic',
    base: 'Strat termic de bază',
    jacket_3s: 'Geacă 3 sezoane, cu liner subțire',
    jacket_std: 'Geacă textil sau piele cu protecții',
    jacket_mesh: 'Geacă mesh ventilată cu protecții',
    hydration: 'Apă: cel puțin 500 ml pe oră',
    gloves_winter: 'Mănuși de iarnă sau încălzite',
    gloves_thermal: 'Mănuși cu dublură termică',
    gloves_std: 'Mănuși de moto cu protecții',
    pants_winter: 'Pantaloni cu liner termic și protecții CE',
    pants_cool: 'Pantaloni de moto cu protecții, liner opțional',
    pants_std: 'Pantaloni de moto cu protecții',
    visor_full: 'Vizor închis complet și guler pentru gât',
    visor_half: 'Vizor închis la viteze mari',
    vest: 'Vestă reflectorizantă',
    tyres: 'Verifică aderența și presiunea anvelopelor',
    uv_visor: 'Vizor fumuriu și cremă de protecție solară',
    dark_visor: 'Vizor clar și vestă reflectorizantă',
    whyRain: '{rain}, de la {hour}',
    whyRainNow: '{rain}, acum',
    whyWetHands: 'mâinile ude reduc controlul la frână',
    whyDrops: 'picături pe vizor: {rain}',
    whyExtremeCold: 'resimțit {f}, frig extrem',
    whyHypothermia: 'protecție la hipotermie sub 0°',
    whyCold: 'resimțit {f}, vreme rece',
    whyThermal: 'confort termic la temperaturi scăzute',
    whyCool: 'resimțit {f}, răcoare',
    whyMild: 'resimțit {f}, condiții bune',
    whyHeat: 'resimțit până la {f}, cald',
    whyDehydration: 'risc de deshidratare',
    whyNumb: 'la {f} degetele amorțesc',
    whyColdHands: 'la {f} mâinile se răcesc repede în mers',
    whyAlways: 'protecție la orice temperatură',
    whyPantsWinter: 'protecție termică și la impact',
    whyPantsCool: 'răcoare: protejează genunchii',
    whyImpact: 'protecție la impact',
    whyGustsStrong: 'rafale de {g} km/h, turbulențe puternice',
    whyGusts: 'rafale de {g} km/h',
    whyFog: 'ceață: fii văzut în trafic',
    whyIce: 'risc de gheață pe asfalt',
    whyUv: 'UV {uv} între {from} și {to}',
    whyNight: 'e întuneric acum',
    whySunset: 'apus la {sunset}',
    tagRequired: 'OBLIGATORIU',
    tagRecommended: 'RECOMANDAT',
    tagAdvice: 'SFĂTUIT',
  },
  {
    rain_suit: 'Rain suit',
    rain_gloves: 'Waterproof gloves',
    pinlock: 'Anti-fog Pinlock and a visor cloth',
    jacket_winter: 'Winter jacket with CE armour and thermal liner',
    base_full: 'Full thermal base layer (top and bottoms)',
    jacket_liner: '3-season jacket with thermal liner',
    base: 'Thermal base layer',
    jacket_3s: '3-season jacket with a thin liner',
    jacket_std: 'Textile or leather jacket with armour',
    jacket_mesh: 'Vented mesh jacket with armour',
    hydration: 'Water: at least 500 ml per hour',
    gloves_winter: 'Winter or heated gloves',
    gloves_thermal: 'Gloves with thermal lining',
    gloves_std: 'Motorcycle gloves with armour',
    pants_winter: 'Trousers with thermal liner and CE armour',
    pants_cool: 'Motorcycle trousers with armour, optional liner',
    pants_std: 'Motorcycle trousers with armour',
    visor_full: 'Fully closed visor and neck collar',
    visor_half: 'Closed visor at speed',
    vest: 'Reflective vest',
    tyres: 'Check tyre grip and pressure',
    uv_visor: 'Tinted visor and sunscreen',
    dark_visor: 'Clear visor and reflective vest',
    whyRain: '{rain}, from {hour}',
    whyRainNow: '{rain}, now',
    whyWetHands: 'wet hands reduce braking control',
    whyDrops: 'drops on the visor: {rain}',
    whyExtremeCold: 'feels like {f}, extreme cold',
    whyHypothermia: 'hypothermia protection below 0°',
    whyCold: 'feels like {f}, cold weather',
    whyThermal: 'thermal comfort in low temperatures',
    whyCool: 'feels like {f}, cool',
    whyMild: 'feels like {f}, good conditions',
    whyHeat: 'feels like up to {f}, hot',
    whyDehydration: 'risk of dehydration',
    whyNumb: 'at {f} fingers go numb',
    whyColdHands: 'at {f} hands cool down fast at speed',
    whyAlways: 'protection at any temperature',
    whyPantsWinter: 'thermal and impact protection',
    whyPantsCool: 'cool weather: protects the knees',
    whyImpact: 'impact protection',
    whyGustsStrong: 'gusts of {g} km/h, strong turbulence',
    whyGusts: 'gusts of {g} km/h',
    whyFog: 'fog: be seen in traffic',
    whyIce: 'ice risk on the asphalt',
    whyUv: 'UV {uv} between {from} and {to}',
    whyNight: 'it is dark now',
    whySunset: 'sunset at {sunset}',
    tagRequired: 'REQUIRED',
    tagRecommended: 'RECOMMENDED',
    tagAdvice: 'ADVISED',
  },
);
