import { defineStrings } from '../../../lib/i18n';

// Sentences built by the pure verdict / cause helpers (no React), so they can
// be unit-tested in both languages. Rain is ALWAYS probability plus amount.
export const TEXTS = defineStrings(
  {
    goIdeal: 'Da. Drum liber.',
    goOk: 'Da.',
    goRain: 'Da. Cel mult câteva picături.',
    goRainLight: 'Da, dar ia costumul de ploaie.',
    goWind: 'Da, atenție la rafale.',
    goCold: 'Da, dar îmbracă-te gros.',
    goHeat: 'Da, dar e cald.',
    goFog: 'Da, atenție la ceață.',
    goNight: 'Da, dar e noapte.',
    goUntil: 'Da, până la {hour}.',
    notNowLater: 'Nu acum. De la {hour}, da.',
    notNowTomorrow: 'Nu acum. Mâine de la {hour}, da.',
    notToday: 'Nu azi.',
    unknown: 'Fără scor acum.',
    fromHour: 'De la {hour}: {text}',
    tomorrowAt: 'mâine {hour}',
    tomorrowGood: 'Mâine de la {hour} arată bine ({score}).',
    tomorrowBad: 'Nici mâine nu arată bine.',
    dryUntilSunset: 'Uscat până la apus ({sunset}), rafale de cel mult {gust} km/h.',
    dryAhead: 'Uscat în orele următoare, rafale de cel mult {gust} km/h.',
    night: 'E întuneric până la {sunrise}: vizibilitate redusă, fii văzut și atent la animale.',
    nightNoSunrise: 'E întuneric: vizibilitate redusă, fii văzut și atent la animale.',
    rainUpTo: '{p}% șanse, până la {mm} mm/h ({band})',
    rainTraces: '{p}% șanse, dar doar urme ({mm} mm/h)',
    rainNoAmount: '{p}% șanse, fără cantitate măsurabilă (sub 0,1 mm/h)',
    rainAmountOnly: 'până la {mm} mm/h ({band})',
    causeStorm: 'furtună, {rain}',
    causeSnow: 'ninsoare, resimțit {feels}',
    causeIce: 'ploaie care îngheață, risc de polei',
    causeFog: 'ceață, vizibilitate {vis}',
    causeFogPlain: 'ceață',
    causeWind: 'rafale de până la {gust} km/h',
    causeCold: 'frig, resimțit {feels}',
    causeHeat: 'caniculă, resimțit {feels}',
    causeColdWet: 'frig și ploaie, resimțit {feels}, {rain}',
    causeFrost: 'risc de polei pe carosabil (asfalt {road})',
  },
  {
    goIdeal: 'Yes. Clear road.',
    goOk: 'Yes.',
    goRain: 'Yes. A few drops at most.',
    goRainLight: 'Yes, but pack the rain suit.',
    goWind: 'Yes, mind the gusts.',
    goCold: 'Yes, but dress warm.',
    goHeat: 'Yes, but it is hot.',
    goFog: 'Yes, mind the fog.',
    goNight: 'Yes, but it is dark.',
    goUntil: 'Yes, until {hour}.',
    notNowLater: 'Not now. From {hour}, yes.',
    notNowTomorrow: 'Not now. Tomorrow from {hour}, yes.',
    notToday: 'Not today.',
    unknown: 'No score right now.',
    fromHour: 'From {hour}: {text}',
    tomorrowAt: 'tomorrow {hour}',
    tomorrowGood: 'Tomorrow from {hour} looks good ({score}).',
    tomorrowBad: 'Tomorrow does not look good either.',
    dryUntilSunset: 'Dry until sunset ({sunset}), gusts up to {gust} km/h.',
    dryAhead: 'Dry for the next hours, gusts up to {gust} km/h.',
    night: 'Dark until {sunrise}: poor visibility, be seen and watch for animals.',
    nightNoSunrise: 'Dark: poor visibility, be seen and watch for animals.',
    rainUpTo: '{p}% chance, up to {mm} mm/h ({band})',
    rainTraces: '{p}% chance, but only traces ({mm} mm/h)',
    rainNoAmount: '{p}% chance, no measurable amount (below 0.1 mm/h)',
    rainAmountOnly: 'up to {mm} mm/h ({band})',
    causeStorm: 'thunderstorm, {rain}',
    causeSnow: 'snow, feels like {feels}',
    causeIce: 'freezing rain, black ice risk',
    causeFog: 'fog, visibility {vis}',
    causeFogPlain: 'fog',
    causeWind: 'gusts up to {gust} km/h',
    causeCold: 'cold, feels like {feels}',
    causeHeat: 'heat, feels like {feels}',
    causeColdWet: 'cold and wet, feels like {feels}, {rain}',
    causeFrost: 'black ice risk on the road (asphalt {road})',
  },
);

// Warning banners and the rain card's plain-language consequence.
export const ALERT_TEXTS = defineStrings(
  {
    warnStormNow: 'Furtună acum',
    warnStormAt: 'Furtună de la {hour}',
    warnIceNow: 'Ploaie care îngheață acum: risc de polei',
    warnIceAt: 'Ploaie care îngheață de la {hour}: risc de polei',
    warnFrostNow: 'Risc de polei pe carosabil acum',
    warnFrostAt: 'Risc de polei pe carosabil de la {hour}',
    warnSnowNow: 'Ninge acum',
    warnSnowAt: 'Ninsoare de la {hour}',
    warnWindNow: 'Rafale puternice acum: {gust} km/h',
    warnWindAt: 'Rafale de până la {gust} km/h de la {hour}',
    warnFogNow: 'Ceață acum: vizibilitate {vis}',
    warnFogAt: 'Ceață de la {hour}: vizibilitate {vis}',
    consequenceDry: 'Fără ploaie în următoarele 24 de ore.',
    consequenceDryChance: 'Fără cantitate măsurabilă: cele {p}% înseamnă un scenariu izolat, asfaltul rămâne uscat.',
    consequenceUrme: 'Cantitate foarte mică: {total} mm în total, în {hours} h. Câteva picături pe vizor, fără costum de ploaie.',
    consequenceSlaba: 'Aproximativ {total} mm în total, în {hours} h. Asfalt ud și frânare mai lungă: ia costumul de ploaie.',
    consequenceModerata: 'Aproximativ {total} mm în total, în {hours} h. Asfalt ud și vizibilitate redusă: costum de ploaie obligatoriu.',
    consequencePuternica: 'Aproximativ {total} mm în total, în {hours} h. Risc de acvaplanare și vizibilitate slabă: amână drumul.',
    unlikelyPrefix: 'Puțin probabil ({p}%). Dacă totuși plouă: ',
  },
  {
    warnStormNow: 'Thunderstorm now',
    warnStormAt: 'Thunderstorm from {hour}',
    warnIceNow: 'Freezing rain now: black ice risk',
    warnIceAt: 'Freezing rain from {hour}: black ice risk',
    warnFrostNow: 'Black ice risk on the road now',
    warnFrostAt: 'Black ice risk on the road from {hour}',
    warnSnowNow: 'Snowing now',
    warnSnowAt: 'Snow from {hour}',
    warnWindNow: 'Strong gusts now: {gust} km/h',
    warnWindAt: 'Gusts up to {gust} km/h from {hour}',
    warnFogNow: 'Fog now: visibility {vis}',
    warnFogAt: 'Fog from {hour}: visibility {vis}',
    consequenceDry: 'No rain in the next 24 hours.',
    consequenceDryChance: 'No measurable amount: the {p}% is an isolated scenario, the road stays dry.',
    consequenceUrme: 'Very little water: {total} mm in total over {hours} h. A few drops on the visor, no rain suit needed.',
    consequenceSlaba: 'About {total} mm in total over {hours} h. Wet asphalt and longer braking: pack the rain suit.',
    consequenceModerata: 'About {total} mm in total over {hours} h. Wet asphalt and poor visibility: rain suit required.',
    consequencePuternica: 'About {total} mm in total over {hours} h. Aquaplaning risk and poor visibility: postpone the ride.',
    unlikelyPrefix: 'Unlikely ({p}%). If it does rain: ',
  },
);
