import { defineStrings } from '../../lib/i18n';

export const S_PLACE = defineStrings(
  {
    changePlace: 'Schimbă locul (acum {name})',
    locate: 'Locația mea',
    locating: 'Caut locația…',
    search: 'Caută o localitate',
    sheetTitle: 'Alege locul',
    searchLabel: 'Caută o localitate',
    searchHint: 'Poți scrie și „sat, județ”, de exemplu Sâmbăta, Brașov.',
    searching: 'Caut…',
    noResults: 'Niciun rezultat pentru „{q}”.',
    searchError: 'Căutarea nu a mers. Verifică conexiunea și încearcă din nou.',
    results: 'Rezultate',
    current: 'Acum vezi',
    favorite: 'Adaugă la favorite',
    unfavorite: 'Scoate din favorite',
    share: 'Trimite locul',
    favorites: 'Favorite',
    noFavorites: 'Nicio localitate salvată. Atinge steaua ca să adaugi locul curent.',
    removeFavorite: 'Șterge {name} din favorite',
    linkCopied: 'Link copiat.',
    shareFailed: 'Nu am putut trimite linkul.',
    shareText: 'Vremea pentru moto în {name}',
    sourcesOne: '1 sursă',
    sourcesMany: '{n} surse',
    refreshing: 'se actualizează',
    geoDenied: 'Accesul la locație e blocat. Permite-l din setările browserului sau caută orașul.',
    geoTimeout: 'Locația nu a răspuns la timp. Încearcă din nou sau caută orașul.',
    geoUnavailable: 'Nu am putut afla locația acum.',
    geoUnsupported: 'Browserul nu oferă localizare. Caută orașul.',
  },
  {
    changePlace: 'Change place (now {name})',
    locate: 'My location',
    locating: 'Finding your location…',
    search: 'Search for a place',
    sheetTitle: 'Choose a place',
    searchLabel: 'Search for a place',
    searchHint: 'You can also type "village, county", for example Sâmbăta, Brașov.',
    searching: 'Searching…',
    noResults: 'No results for "{q}".',
    searchError: 'Search failed. Check your connection and try again.',
    results: 'Results',
    current: 'Now showing',
    favorite: 'Add to favourites',
    unfavorite: 'Remove from favourites',
    share: 'Share this place',
    favorites: 'Favourites',
    noFavorites: 'No saved places yet. Tap the star to add the current one.',
    removeFavorite: 'Remove {name} from favourites',
    linkCopied: 'Link copied.',
    shareFailed: 'Could not share the link.',
    shareText: 'Riding weather in {name}',
    sourcesOne: '1 source',
    sourcesMany: '{n} sources',
    refreshing: 'refreshing',
    geoDenied: 'Location access is blocked. Allow it in the browser settings or search for the town.',
    geoTimeout: 'Location did not answer in time. Try again or search for the town.',
    geoUnavailable: 'Could not get your location right now.',
    geoUnsupported: 'This browser has no location support. Search for the town.',
  },
);
