import { defineStrings } from '../../lib/i18n';

// Copy for the route actions, their sheets, saved routes, ride stats and hazards.
export const AS = defineStrings(
  {
    actSave: 'Salvează',
    actSaveAria: 'Salvează traseul',
    actGpx: 'GPX',
    actGpxAria: 'Descarcă traseul ca GPX',
    actLog: 'Tura',
    actLogAria: 'Înregistrează tura',
    actHazard: 'Pericol',
    actHazardAria: 'Raportează un pericol',
    signedOutTitle: 'Intră în cont',
    signedOutBody: 'Ca să salvezi rute, să înregistrezi ture și să raportezi pericole ai nevoie de un cont MotoMeteo. GPX-ul merge și fără cont.',
    signedOutNote: 'Salvarea, turele și raportările cer cont.',
    goToAccount: 'Mergi la cont',
    saveTitle: 'Salvează traseul',
    saveName: 'Numele traseului',
    saveNameHint: 'Între 2 și 80 de caractere',
    saveNameError: 'Numele trebuie să aibă între 2 și 80 de caractere.',
    saveOk: 'Traseu salvat.',
    saveErr: 'Nu am putut salva traseul.',
    gpxOk: 'Fișierul GPX a fost descărcat.',
    gpxErr: 'Nu am putut crea fișierul GPX.',
    logTitle: 'Înregistrează tura',
    logIntro: 'Adaug tura în statisticile tale:',
    logDistance: 'Distanță',
    logDuration: 'Durată la {v} km/h',
    logAvg: 'Scor mediu',
    logWorst: 'Cel mai slab scor',
    logGust: 'Rafală maximă',
    logPrecip: 'Ploaie maximă',
    logConfirm: 'Înregistrează',
    logOk: 'Tura a fost înregistrată.',
    logErr: 'Nu am putut înregistra tura.',
    hzReportTitle: 'Raportează un pericol',
    hzType: 'Ce e pe drum',
    hzSeverity: 'Cât de grav',
    hzDesc: 'Descriere',
    hzDescHint: '{n} din 220 de caractere, minim 3',
    hzDescError: 'Scrie între 3 și 220 de caractere.',
    hzTtl: 'Cât timp rămâne afișat',
    hzTtlOption: '{n} h',
    hzWhere: 'Unde',
    hzGps: 'Poziția mea (GPS)',
    hzSend: 'Trimite',
    hzOk: 'Pericol raportat. Mulțumim!',
    hzErr: 'Nu am putut trimite raportul.',
    hzRate: 'Ai trimis multe rapoarte în ultima oră. Încearcă mai târziu.',
    hzGpsFail: 'Nu am putut afla poziția. Alege un punct de pe traseu.',
    hzTitle: 'Pericole pe traseu',
    hzNone: 'Niciun pericol raportat lângă traseu.',
    hzLoading: 'Caut pericole raportate…',
    hzError: 'Pericolele raportate nu s-au încărcat.',
    hzOnRoad: 'km {km}, pe drum',
    hzOffRoad: 'km {km}, la {d} km de drum',
    hzSev: 'gravitate {n} din 5, {word}',
    ageNow: 'raportat chiar acum',
    ageMin: 'raportat acum {n} min',
    ageHours: 'raportat acum {n} h',
    ageDays: 'raportat acum {n} zile',
    sev1: 'minor',
    sev2: 'scăzut',
    sev3: 'mediu',
    sev4: 'ridicat',
    sev5: 'grav',
    type_gravel: 'Pietriș',
    type_ice: 'Polei',
    type_flood: 'Apă pe carosabil',
    type_accident: 'Accident',
    type_animals: 'Animale',
    type_roadworks: 'Lucrări',
    type_other: 'Altceva',
    savedTitle: 'Rute salvate',
    savedEmpty: 'Nu ai rute salvate. Calculează un traseu și apasă Salvează.',
    savedErr: 'Rutele salvate nu s-au încărcat.',
    savedLoad: 'Încarcă traseul {name}',
    savedDelete: 'Șterge traseul {name}',
    savedLoading: 'Încarc traseul…',
    savedLoadErr: 'Nu am găsit „{name}” din traseul salvat.',
    deleteTitle: 'Ștergi traseul?',
    deleteBody: '„{name}” dispare din rutele salvate. Nu se poate anula.',
    deleteOk: 'Traseu șters.',
    deleteErr: 'Nu am putut șterge traseul.',
    statsTitle: 'Turele tale',
    statsRides: 'Ture',
    statsDistance: 'Distanță',
    statsTime: 'Timp în șa',
    statsAvg: 'Scor mediu',
    statsRecent: 'Ultimele ture',
    statsEmpty: 'Încă nicio tură. După ce calculezi un traseu, apasă „Tura”.',
    statsErr: 'Statisticile nu s-au încărcat.',
  },
  {
    actSave: 'Save',
    actSaveAria: 'Save the route',
    actGpx: 'GPX',
    actGpxAria: 'Download the route as GPX',
    actLog: 'Ride',
    actLogAria: 'Log this ride',
    actHazard: 'Hazard',
    actHazardAria: 'Report a hazard',
    signedOutTitle: 'Sign in',
    signedOutBody: 'Saving routes, logging rides and reporting hazards need a MotoMeteo account. GPX export works without one.',
    signedOutNote: 'Saving, rides and reports need an account.',
    goToAccount: 'Go to account',
    saveTitle: 'Save the route',
    saveName: 'Route name',
    saveNameHint: 'Between 2 and 80 characters',
    saveNameError: 'The name needs 2 to 80 characters.',
    saveOk: 'Route saved.',
    saveErr: 'Could not save the route.',
    gpxOk: 'GPX file downloaded.',
    gpxErr: 'Could not create the GPX file.',
    logTitle: 'Log this ride',
    logIntro: 'This ride goes into your stats:',
    logDistance: 'Distance',
    logDuration: 'Time at {v} km/h',
    logAvg: 'Average score',
    logWorst: 'Weakest score',
    logGust: 'Strongest gust',
    logPrecip: 'Most rain',
    logConfirm: 'Log ride',
    logOk: 'Ride logged.',
    logErr: 'Could not log the ride.',
    hzReportTitle: 'Report a hazard',
    hzType: 'What is on the road',
    hzSeverity: 'How bad',
    hzDesc: 'Description',
    hzDescHint: '{n} of 220 characters, at least 3',
    hzDescError: 'Write 3 to 220 characters.',
    hzTtl: 'Show it for',
    hzTtlOption: '{n} h',
    hzWhere: 'Where',
    hzGps: 'My position (GPS)',
    hzSend: 'Send',
    hzOk: 'Hazard reported. Thank you!',
    hzErr: 'Could not send the report.',
    hzRate: 'You sent many reports in the last hour. Try again later.',
    hzGpsFail: 'Could not get your position. Pick a point on the route.',
    hzTitle: 'Hazards on the route',
    hzNone: 'No hazards reported near the route.',
    hzLoading: 'Looking for reported hazards…',
    hzError: 'Reported hazards did not load.',
    hzOnRoad: 'km {km}, on the road',
    hzOffRoad: 'km {km}, {d} km off the road',
    hzSev: 'severity {n} of 5, {word}',
    ageNow: 'reported just now',
    ageMin: 'reported {n} min ago',
    ageHours: 'reported {n} h ago',
    ageDays: 'reported {n} days ago',
    sev1: 'minor',
    sev2: 'low',
    sev3: 'medium',
    sev4: 'high',
    sev5: 'severe',
    type_gravel: 'Gravel',
    type_ice: 'Ice',
    type_flood: 'Water on the road',
    type_accident: 'Accident',
    type_animals: 'Animals',
    type_roadworks: 'Roadworks',
    type_other: 'Something else',
    savedTitle: 'Saved routes',
    savedEmpty: 'No saved routes yet. Plan a route and tap Save.',
    savedErr: 'Saved routes did not load.',
    savedLoad: 'Load route {name}',
    savedDelete: 'Delete route {name}',
    savedLoading: 'Loading the route…',
    savedLoadErr: 'Could not find "{name}" from the saved route.',
    deleteTitle: 'Delete this route?',
    deleteBody: '"{name}" will be removed from your saved routes. This cannot be undone.',
    deleteOk: 'Route deleted.',
    deleteErr: 'Could not delete the route.',
    statsTitle: 'Your rides',
    statsRides: 'Rides',
    statsDistance: 'Distance',
    statsTime: 'Time riding',
    statsAvg: 'Average score',
    statsRecent: 'Recent rides',
    statsEmpty: 'No rides yet. After planning a route, tap "Ride".',
    statsErr: 'Stats did not load.',
  },
);
