import { defineStrings } from '../../lib/i18n';

// Planner copy: stops, departure, calculation, sweep, map and timeline.
// Actions, sheets, saved routes, stats and hazards live in actionStrings.ts.
export const RS = defineStrings(
  {
    title: 'Traseu',
    savedButton: 'Salvate · {n}',
    stopsTitle: 'Opriri',
    roleOrigin: 'plecare',
    roleVia: 'oprire',
    roleDestination: 'destinație',
    fieldOrigin: 'Plecare',
    fieldVia: 'Oprirea {n}',
    fieldDestination: 'Destinație',
    placeholderOrigin: 'De unde pleci?',
    placeholderVia: 'Prin ce localitate treci?',
    placeholderDestination: 'Unde ajungi?',
    suggestionsFor: 'Sugestii pentru {field}',
    noSuggestions: 'Nicio localitate găsită. Pentru sate scrie „sat, județ”.',
    searchFailed: 'Căutarea nu merge acum. Verifică conexiunea.',
    searching: 'Caut…',
    myLocation: 'Locația mea',
    useMyLocationFor: 'Folosește locația mea pentru {field}',
    locateFailed: 'Nu am putut afla poziția. Scrie localitatea.',
    locateDenied: 'Accesul la locație e blocat. Scrie localitatea.',
    addStop: 'Adaugă oprire',
    maxStops: 'max. {n}',
    reorder: 'Ordine',
    reorderDone: 'Gata',
    moveUp: 'Mută „{name}” mai sus',
    moveDown: 'Mută „{name}” mai jos',
    removeStop: 'Elimină „{name}”',
    emptyStop: 'oprire necompletată',
    departureTitle: 'Plecare',
    dayLabel: 'Ziua',
    today: 'Azi',
    tomorrow: 'Mâine',
    timeLabel: 'Ora',
    timeHint: 'ora locală la plecare',
    earlier: 'Cu 30 de minute mai devreme',
    later: 'Cu 30 de minute mai târziu',
    speedLabel: 'Medie',
    speedAria: 'Viteza medie pe drum',
    speedUnit: '{v} km/h',
    calculate: 'Calculează traseul',
    recalculate: 'Recalculează',
    stale: 'Ai schimbat opririle. Recalculează ca să vezi vremea pe noul traseu.',
    needTwo: 'Completează plecarea și destinația.',
    stepGeocoding: 'Caut localitățile…',
    stepRouting: 'Caut drumul…',
    stepWeather: 'Vremea pe drum: {done} din {total} puncte',
    errNoRoute: 'Nu am găsit un drum cu mașina între aceste opriri. Verifică localitățile.',
    errGeocode: 'Nu am găsit localitatea „{name}”. Alege una din sugestii.',
    errNetwork: 'Nu am putut calcula traseul. Verifică conexiunea.',
    errWeather: 'Vremea nu s-a încărcat pentru {n} puncte.',
    retryWeather: 'Reîncearcă vremea',
    emptyTitle: 'Vremea pe tot drumul, la ora la care treci',
    emptyBody: 'Pune plecarea, destinația și până la 3 opriri, apoi ziua și ora. Vezi scorul moto, ploaia și rafalele în fiecare punct, exact când ajungi acolo.',
    emptyExample: 'Exemplu: București → Pitești → Sibiu, la 75 km/h',
    tryExample: 'Încearcă exemplul',
    mapLabel: 'Harta traseului, colorată după scorul moto pe fiecare porțiune',
    mapLegend: 'Scor pe drum',
    summary: '{km} km · {dur}',
    durHm: '{h} h {m}',
    durM: '{m} min',
    sweepTitle: 'Când pleci',
    sweepGo: 'Pleacă la {time}',
    sweepGain: 'Cel mai slab punct urcă de la {from} la {to} ({place}).',
    sweepSame: 'Ora aleasă e cea mai bună',
    sweepSameBody: 'Cel mai slab punct rămâne la {score} ({place}). Nicio altă plecare între 05:00 și 20:00 nu iese mai bine.',
    sweepNone: 'Nu mai sunt plecări posibile azi între 05:00 și 20:00. Alege altă zi.',
    sweepWaiting: 'Compar orele de plecare când se încarcă toate punctele…',
    sweepBest: 'cea mai bună',
    sweepChosen: 'ora aleasă',
    sweepChart: 'Cel mai slab scor de pe traseu pentru fiecare plecare între 05:00 și 20:00. Cea mai bună: {best}, scor {bestScore}. Aleasă: {chosen}, scor {chosenScore}.',
    adopt: 'Plec la {time}',
    keep: 'Rămân la {time}',
    wpTitle: 'Vremea pe drum',
    wpKm: 'km {km}',
    wpGust: 'rafale {v} km/h',
    wpError: 'Vremea nu s-a încărcat aici.',
    wpNoData: 'Fără prognoză pentru ora asta.',
    wpScore: 'scor moto {score}, {label}',
    afterStop: 'după {stop}',
    rainChance: 'ploaie: {prob}% șanse · {mm} mm/h, {band}',
    rainAmount: 'ploaie: {mm} mm/h, {band}',
    rainNone: 'fără ploaie',
    rainNoneChance: 'fără ploaie ({prob}% șanse, 0 mm)',
  },
  {
    title: 'Route',
    savedButton: 'Saved · {n}',
    stopsTitle: 'Stops',
    roleOrigin: 'start',
    roleVia: 'stop',
    roleDestination: 'destination',
    fieldOrigin: 'Start',
    fieldVia: 'Stop {n}',
    fieldDestination: 'Destination',
    placeholderOrigin: 'Where do you start?',
    placeholderVia: 'Which town do you pass?',
    placeholderDestination: 'Where are you going?',
    suggestionsFor: 'Suggestions for {field}',
    noSuggestions: 'No place found. For villages type "village, county".',
    searchFailed: 'Search is not working right now. Check your connection.',
    searching: 'Searching…',
    myLocation: 'My location',
    useMyLocationFor: 'Use my location for {field}',
    locateFailed: 'Could not get your position. Type the place instead.',
    locateDenied: 'Location access is blocked. Type the place instead.',
    addStop: 'Add stop',
    maxStops: 'max. {n}',
    reorder: 'Order',
    reorderDone: 'Done',
    moveUp: 'Move "{name}" up',
    moveDown: 'Move "{name}" down',
    removeStop: 'Remove "{name}"',
    emptyStop: 'empty stop',
    departureTitle: 'Departure',
    dayLabel: 'Day',
    today: 'Today',
    tomorrow: 'Tomorrow',
    timeLabel: 'Time',
    timeHint: 'local time at the start',
    earlier: '30 minutes earlier',
    later: '30 minutes later',
    speedLabel: 'Average',
    speedAria: 'Average speed on the road',
    speedUnit: '{v} km/h',
    calculate: 'Plan the route',
    recalculate: 'Recalculate',
    stale: 'You changed the stops. Recalculate to see the weather on the new route.',
    needTwo: 'Fill in the start and the destination.',
    stepGeocoding: 'Looking up the places…',
    stepRouting: 'Finding the road…',
    stepWeather: 'Weather on the road: {done} of {total} points',
    errNoRoute: 'No driving route found between these stops. Check the places.',
    errGeocode: 'Could not find "{name}". Pick one of the suggestions.',
    errNetwork: 'Could not plan the route. Check your connection.',
    errWeather: 'Weather did not load for {n} points.',
    retryWeather: 'Retry the weather',
    emptyTitle: 'Weather along the whole road, at the time you pass',
    emptyBody: 'Add the start, the destination and up to 3 stops, then the day and time. You get the moto score, rain and gusts at every point, right when you get there.',
    emptyExample: 'Example: București → Pitești → Sibiu, at 75 km/h',
    tryExample: 'Try the example',
    mapLabel: 'Route map, coloured by the moto score of each stretch',
    mapLegend: 'Score on the road',
    summary: '{km} km · {dur}',
    durHm: '{h} h {m}',
    durM: '{m} min',
    sweepTitle: 'When to leave',
    sweepGo: 'Leave at {time}',
    sweepGain: 'The weakest point goes up from {from} to {to} ({place}).',
    sweepSame: 'Your time is the best one',
    sweepSameBody: 'The weakest point stays at {score} ({place}). No other departure between 05:00 and 20:00 does better.',
    sweepNone: 'No departures left today between 05:00 and 20:00. Pick another day.',
    sweepWaiting: 'Comparing departure times once every point has loaded…',
    sweepBest: 'best',
    sweepChosen: 'your time',
    sweepChart: 'Weakest score on the route for each departure between 05:00 and 20:00. Best: {best}, score {bestScore}. Yours: {chosen}, score {chosenScore}.',
    adopt: 'Leave at {time}',
    keep: 'Keep {time}',
    wpTitle: 'Weather on the road',
    wpKm: 'km {km}',
    wpGust: 'gusts {v} km/h',
    wpError: 'Weather did not load here.',
    wpNoData: 'No forecast for this hour.',
    wpScore: 'moto score {score}, {label}',
    afterStop: 'after {stop}',
    rainChance: 'rain: {prob}% chance · {mm} mm/h, {band}',
    rainAmount: 'rain: {mm} mm/h, {band}',
    rainNone: 'no rain',
    rainNoneChance: 'no rain ({prob}% chance, 0 mm)',
  },
);
